
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

// Helper function to format date
const formatDate = (date: string | Date): string => {
  return format(new Date(date), 'MMMM d, yyyy');
};

// Function to create interview PDF
export const generateInterviewPDF = (interviewData: any): jsPDF => {
  // Create a new PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Set font styles
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(44, 62, 80); // Dark blue text

  // Add header
  doc.setFontSize(24);
  doc.text('Interview Feedback', 20, 20);
  
  // Add date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const currentDate = formatDate(interviewData.date || new Date());
  doc.text(`Generated on ${currentDate}`, 20, 30);

  // Add horizontal line
  doc.setDrawColor(41, 128, 185); // Blue line
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // Add interview information
  let lastY = 45; // Starting Y position
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Interview Details', 20, lastY);
  lastY += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  // Role
  doc.setFont('helvetica', 'bold');
  doc.text('Position:', 20, lastY);
  doc.setFont('helvetica', 'normal');
  doc.text(interviewData.role || 'Not specified', 60, lastY);
  lastY += 8;
  
  // Type
  doc.setFont('helvetica', 'bold');
  doc.text('Interview Type:', 20, lastY);
  doc.setFont('helvetica', 'normal');
  doc.text(interviewData.type || 'Not specified', 60, lastY);
  lastY += 8;
  
  // Duration
  doc.setFont('helvetica', 'bold');
  doc.text('Duration:', 20, lastY);
  doc.setFont('helvetica', 'normal');
  doc.text(interviewData.duration || 'Not specified', 60, lastY);
  lastY += 15; // Add space before next section
  
  // Score section
  if (interviewData.results && interviewData.results.overallScore) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Overall Score', 20, lastY);
    lastY += 8;
    
    doc.setFontSize(24);
    doc.setTextColor(41, 128, 185); // Blue text for score
    const score = `${interviewData.results.overallScore}/100`;
    doc.text(score, 20, lastY);
    doc.setTextColor(44, 62, 80); // Reset text color
    lastY += 15;
  }
  
  // Strengths section
  if (interviewData.results && interviewData.results.strengths && interviewData.results.strengths.length > 0) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Strengths', 20, lastY);
    lastY += 8;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const strengths = interviewData.results.strengths;
    
    // Use autoTable for strengths list
    const strengthsTableOutput = autoTable(doc, {
      startY: lastY,
      head: [['Strengths']],
      body: strengths.map((strength: string) => [strength]),
      theme: 'grid',
      headStyles: {
        fillColor: [231, 247, 255],
        textColor: [44, 62, 80],
        fontStyle: 'bold'
      },
      styles: {
        overflow: 'linebreak',
        cellPadding: 4,
        cellWidth: 'auto'
      },
      margin: { left: 20, right: 20 }
    });
    
    // Update the Y position for the next section
    lastY = (strengthsTableOutput?.finalY || lastY) + 15;
  }
  
  // Areas for improvement section
  if (interviewData.results && interviewData.results.improvements && interviewData.results.improvements.length > 0) {
    // Check if we need a new page
    if (lastY > 250) {
      doc.addPage();
      lastY = 20;
    }
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Areas for Improvement', 20, lastY);
    lastY += 8;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const improvements = interviewData.results.improvements;
    
    // Use autoTable for improvements list
    const improvementsTableOutput = autoTable(doc, {
      startY: lastY,
      head: [['Areas for Improvement']],
      body: improvements.map((improvement: string) => [improvement]),
      theme: 'grid',
      headStyles: {
        fillColor: [255, 243, 224],
        textColor: [44, 62, 80],
        fontStyle: 'bold'
      },
      styles: {
        overflow: 'linebreak',
        cellPadding: 4,
        cellWidth: 'auto'
      },
      margin: { left: 20, right: 20 }
    });
    
    // Update the Y position for the next section
    lastY = (improvementsTableOutput?.finalY || lastY) + 15;
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by InterviewAI', 20, 290);
    doc.text(`Page ${i} of ${pageCount}`, 180, 290);
  }
  
  return doc;
};

// Export a function to generate and save the PDF
export const generatePdf = (interviewData: any): void => {
  const doc = generateInterviewPDF(interviewData);
  doc.save(`interview-feedback-${new Date().getTime()}.pdf`);
};
