
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InterviewResults {
  overallScore: number;
  strengths: string[];
  improvements: string[];
  completedAt: string;
}

interface Interview {
  id: string;
  title: string;
  date: string;
  duration: string;
  role: string;
  position?: string;
  type: 'technical' | 'behavioral' | 'mixed';
  completed: boolean;
  score?: number;
  results?: InterviewResults;
}

export const generatePdf = (interview: Interview) => {
  // Create a new PDF document
  const doc = new jsPDF();
  
  // Set document properties
  doc.setProperties({
    title: `Interview Report - ${interview.title}`,
    subject: 'Interview Performance Report',
    author: 'InterviewAI',
    creator: 'InterviewAI Application'
  });

  // Add header
  doc.setFontSize(22);
  doc.setTextColor(41, 37, 36); // Dark gray
  doc.text('Interview Performance Report', 105, 20, { align: 'center' });
  
  // Add logo placeholder
  // This would normally be an image, but we'll just draw a colored rectangle
  doc.setFillColor(79, 70, 229); // Indigo color
  doc.rect(20, 10, 30, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('InterviewAI', 35, 20, { align: 'center' });

  // Interview details section
  doc.setFontSize(14);
  doc.setTextColor(41, 37, 36);
  doc.text('Interview Details', 20, 40);
  
  doc.setFontSize(10);
  doc.setTextColor(75, 85, 99);
  
  const detailsData = [
    ['Title', interview.title],
    ['Role', interview.position || interview.role],
    ['Date', interview.date],
    ['Duration', interview.duration],
    ['Type', interview.type.charAt(0).toUpperCase() + interview.type.slice(1)]
  ];
  
  autoTable(doc, {
    startY: 45,
    head: [],
    body: detailsData,
    theme: 'plain',
    styles: {
      cellPadding: 2,
      fontSize: 10
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 30 },
      1: { cellWidth: 150 }
    }
  });

  // Performance Score
  const score = interview.score || interview.results?.overallScore || 0;
  
  // Performance score background
  doc.setFillColor(237, 233, 254);
  doc.roundedRect(15, 85, 180, 30, 3, 3, 'F');
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(14);
  doc.text('Performance Score', 20, 95);
  doc.setFontSize(24);
  doc.text(`${score.toFixed(1)}/10`, 160, 95, { align: 'right' });
  
  let lastY = 130;
  
  // Strengths
  if (interview.results?.strengths && interview.results.strengths.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(41, 37, 36);
    doc.text('Strengths', 20, lastY);
    
    const strengths = interview.results.strengths.map((strength, index) => [
      `${index + 1}.`, strength
    ]);
    
    const strengthsTable = autoTable(doc, {
      startY: lastY + 5,
      head: [],
      body: strengths,
      theme: 'plain',
      styles: {
        cellPadding: 2,
        fontSize: 10
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 170 }
      }
    });
    
    // Update the Y position for the next section - use the finalY from the table
    if (strengthsTable.lastAutoTable && strengthsTable.lastAutoTable.finalY) {
      lastY = strengthsTable.lastAutoTable.finalY + 15;
    } else {
      lastY += 25 + (strengths.length * 10);
    }
  }

  // Areas for Improvement
  if (interview.results?.improvements && interview.results.improvements.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(41, 37, 36);
    doc.text('Areas for Improvement', 20, lastY);
    
    const improvements = interview.results.improvements.map((improvement, index) => [
      `${index + 1}.`, improvement
    ]);
    
    autoTable(doc, {
      startY: lastY + 5,
      head: [],
      body: improvements,
      theme: 'plain',
      styles: {
        cellPadding: 2,
        fontSize: 10
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 170 }
      }
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by InterviewAI | ${new Date().toLocaleDateString()}`,
      105, 
      285, 
      { align: 'center' }
    );
  }
  
  // Save the PDF with the interview title
  doc.save(`InterviewAI-Report-${interview.title.replace(/\s+/g, '-')}.pdf`);
  
  return doc;
};
