// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgwrnbcmmajitlsijwpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnd3JuYmNtbWFqaXRsc2lqd3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTczODQsImV4cCI6MjA2MjE3MzM4NH0.eJWnN60u8vEBqpEpwu2Rw_UhgLWrLwozAj1Fq2VK60k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);